AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: serverless-survey-external-config
    Description: Serverless survey with Python 3.8 runtime and external config file
      sourced from Amazon S3 bucket. This is a fork of https://serverlessrepo.aws.amazon.com/applications/us-east-1/194383749778/serverless-survey.
    Author: Vinod Shukla
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-cfn-samples/serverless-survey/fa818a259cbed7ce8bc2a22d35a464fc
    ReadmeUrl: s3://aws-cfn-samples/serverless-survey/bab3d9580ac4bec6438b3055a1343823
    Labels:
    - lambda
    - survey
    - serverless
    - html
    - dynamodb
    HomePageUrl: https://github.com/vsnyc/serverless-survey
    SemanticVersion: '0.0.1'
    SourceCodeUrl: https://github.com/vsnyc/serverless-survey
Parameters:
  ConfigFileLocation:
    Description: Provide the S3 location of the survey configuration file. For example,
      if the location is "s3://my-config-bucket/config.yaml,"" enter "my-config-bucket/config.yaml.""
    Type: String
Resources:
  SurveyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SurveyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - s3:GetObject
            Resource:
              Fn::Sub: arn:aws:s3:::${ConfigFileLocation}
            Effect: Allow
        PolicyName: config-file-s3-access
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  Survey:
    Type: AWS::Serverless::Function
    Properties:
      Handler: survey.lambda_handler
      CodeUri: s3://aws-cfn-samples/serverless-survey/4b01cf5067c5cebdd83b6c72f00f2343
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - SurveyRole
        - Arn
      Events:
        RestAPI:
          Type: Api
          Properties:
            Path: /newsurvey
            Method: ANY
      Environment:
        Variables:
          ConfigFileLocation:
            Ref: ConfigFileLocation
  SurveySubmit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: survey_submit.lambda_handler
      CodeUri: s3://aws-cfn-samples/serverless-survey/4b01cf5067c5cebdd83b6c72f00f2343
      Runtime: python3.8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: SurveyTable
      Events:
        RestAPI:
          Type: Api
          Properties:
            Path: /submitsurvey
            Method: ANY
      Environment:
        Variables:
          TABLE_NAME:
            Ref: SurveyTable
Outputs:
  SurveyURL:
    Description: Link to your Serverless Survey
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/newsurvey
